import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import '@/css/embla.css';
import Header from '@/app/_components/header';
import Footer from '@/app/_components/footer';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative ">
        <Header />
        {children}
        <Footer />

        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
